### PR TITLE
Use a map instead of if statements.

### PR DESCRIPTION
**Pull request by lf94**

### CODE REVIEW

**Comment by ankitjain28may** [comment]
Thanks @lf94

**Comment by lf94** [comment]
Are you going to merge the pull request?

**Comment by ankitjain28may** [comment]
Yes.. Ofcourse... I will merge it later..!

**Comment by ankitjain28may** [comment]
Thanks @lf94

**Comment by ankitjain28may** [comment]
Its not working try to check it @lf94

**Pull request merged**
